### ISSUE TITLE
Support for reloading changes in node_modules

### ISSUE THREAD

**Issue by jussiarpalahti** [charto/cbuild#1]
I have a use case of developing an app and a library separately. 

However, reloader does not reload files when they change if they are not under src.

I tried using module level node_modules, since node and TypeScript support loading libraries from importing module's folder under node_modules folder.

However config reloader doesn't check there when finding imported paths, and I couldn't get that part working.

So, I have a structure like this:

/node_modules/[for regular libraries]
/src/[my app files]
/src/node_modules/my_library

Is there any way to either get cbuild to check also source folder's node_modules or config reloader to reload also regular node_modules files?

**Comment by jjrv** [comment]
Thanks for letting me check out your current code. The issue was actually on [this line](https://github.com/capaj/chokidar-socket-emitter/blob/0804a1723de5bbc49e412c77847c0505986199c9/server.js#L37) of `chokidar-socket-emitter`. After commenting it out, it sends events for changes also in files under `node_modules`.
